### ISSUE TITLE
Graph View not visible on browser

### ISSUE THREAD

**Issue by apielmicroej** [jenkinsci/pipeline-graph-view-plugin#513]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  ```Jenkins: 2.440.3
OS: Linux - 4.15.0-213-generic
Java: 17.0.10 - Eclipse Adoptium (OpenJDK 64-Bit Server VM)
---
Parameterized-Remote-Trigger:3.1.4
active-directory:2.36
analysis-model-api:9.1.0
ansicolor:0.7.3
ant:497.v94e7d9fffa_b_9
antexec:1.11
antisamy-markup-formatter:162.v0e6ec0fcfcf6
apache-httpcomponents-client-4-api:4.5.14-208.v438351942757
artifactory:4.0.8
asm-api:9.7-33.v4d23ef79fcc8
authentication-tokens:1.4
badge:1.8
blueocean:1.24.0
blueocean-autofavorite:1.2.4
blueocean-bitbucket-pipeline:1.24.0
blueocean-commons:1.24.0
blueocean-config:1.24.0
blueocean-core-js:1.24.0
blueocean-dashboard:1.24.0
blueocean-display-url:2.4.0
blueocean-events:1.24.0
blueocean-git-pipeline:1.24.0
blueocean-github-pipeline:1.24.0
blueocean-i18n:1.24.0
blueocean-jira:1.24.0
blueocean-jwt:1.24.0
blueocean-personalization:1.24.0
blueocean-pipeline-api-impl:1.24.0
blueocean-pipeline-editor:1.24.0
blueocean-pipeline-scm-api:1.24.0
blueocean-rest:1.24.0
blueocean-rest-impl:1.24.0
blueocean-web:1.24.0
bootstrap5-api:5.3.2-3
bouncycastle-api:2.30.1.78.1-248.ve27176eb_46cb_
branch-api:2.1128.v717130d4f816
build-keeper-plugin:1.3
build-name-setter:2.2.1
build-timestamp:1.0.3
build-user-vars-plugin:1.6
caffeine-api:3.1.8-133.v17b_1ff2e0599
checks-api:2.0.2
cloudbees-bitbucket-branch-source:2.9.4
cloudbees-folder:6.858.v898218f3609d
command-launcher:107.v773860566e2e
commons-lang3-api:3.17.0-84.vb_b_938040b_078
commons-text-api:1.12.0-129.v99a_50df237f7
conditional-buildstep:1.4.3
config-file-provider:973.vb_a_80ecb_9a_4d0
coverage:1.10.0
credentials:1378.v81ef4269d764
credentials-binding:681.vf91669a_32e45
custom-tools-plugin:0.7
customized-build-message:1.1
dashboard-view:2.495.v07e81500c3f2
data-tables-api:1.13.6-5
description-setter:1.10
display-url-api:2.204.vf6fddd8a_8b_e9
docker-commons:419.v8e3cd84ef49c
docker-custom-build-environment:1.7.3
docker-java-api:3.2.13-37.vf3411c9828b9
docker-plugin:1.2.9
docker-workflow:580.vc0c340686b_54
durable-task:577.v2a_8a_4b_7c0247
echarts-api:5.4.0-7
email-ext:2.99
envfile:1.2
envinject:2.3.0
envinject-api:1.7
extended-choice-parameter:382.v5697b_32134e8
extended-read-permission:3.2
external-monitor-job:215.v2e88e894db_f8
favorite:2.4.3
file-leak-detector:1.6
filesystem-list-parameter-plugin:0.0.8
flexible-publish:0.16.1
font-awesome-api:6.5.1-2
forensics-api:2.3.0
git:5.2.2
git-client:4.7.0
git-parameter:0.9.13
git-server:1.9
github:1.40.0
github-api:1.321-468.v6a_9f5f2d5a_7e
github-branch-source:1793.v1831e9c68d77
gitlab-api:5.1.0-84.v491924123a_f7
gitlab-branch-source:650.va_d1ce6d01959
gitlab-plugin:1.7.14
gradle:2.12.1
groovy:2.3
groovy-postbuild:2.5
gson-api:2.11.0-41.v019fcf6125dc
handy-uri-templates-2-api:2.1.8-22.v77d5b_75e6953
htmlpublisher:1.31
instance-identity:185.v303dc7c645f9
ionicons-api:74.v93d5eb_813d5f
ivy:2.1
jackson2-api:2.17.0-379.v02de8ec9f64c
jakarta-activation-api:2.1.3-1
jakarta-mail-api:2.1.3-1
javadoc:243.vb_b_503b_b_45537
javax-activation-api:1.2.0-7
javax-mail-api:1.6.2-9
jaxb:2.3.9-1
jdk-tool:73.vddf737284550
jenkins-design-language:1.24.0
jersey2-api:2.44-151.v6df377fff741
jira:3.1.1
jjwt-api:0.11.5-112.ve82dfb_224b_a_d
joda-time-api:2.12.7-29.v5a_b_e3a_82269a_
jquery:1.12.4-1
jquery3-api:3.7.1-2
jsch:0.2.16-86.v42e010d9484b_
json-api:20240303-41.v94e11e6de726
json-path-api:2.9.0-33.v2527142f2e1d
junit:1296.vb_f538b_c88630
keycloak:2.3.2
ldap:2.9
ldapemail:0.8
list-git-branches-parameter:0.0.9
lockable-resources:2.10
mailer:472.vf7c289a_4b_420
matrix-auth:3.2.2
matrix-project:822.824.v14451b_c0fd42
maven-plugin:3.23
mercurial:2.10
metrics:4.2.21-451.vd51df8df52ec
microej:1.2.3
microej-emotional-jenkins-plugin:1.3-SNAPSHOT (private-729f237a-aquillet)
mina-sshd-api-common:2.13.2-125.v200281b_61d59
mina-sshd-api-core:2.13.2-125.v200281b_61d59
nested-view:1.33
nodelabelparameter:1.12.0
okhttp-api:4.11.0-172.vda_da_1feeb_c6e
pam-auth:1.6
parameter-separator:1.3
parameterized-scheduler:0.8
parameterized-trigger:806.vf6fff3e28c3e
pipeline-build-step:488.v8993df156e8d
pipeline-graph-analysis:216.vfd8b_ece330ca_
pipeline-graph-view:243.vc9e11fec486a_
pipeline-groovy-lib:730.ve57b_34648c63
pipeline-input-step:495.ve9c153f6067b_
pipeline-milestone-step:111.v449306f708b_7
pipeline-model-api:2.2214.vb_b_34b_2ea_9b_83
pipeline-model-definition:2.2214.vb_b_34b_2ea_9b_83
pipeline-model-extensions:2.2214.vb_b_34b_2ea_9b_83
pipeline-rest-api:2.34
pipeline-stage-step:312.v8cd10304c27a_
pipeline-stage-tags-metadata:2.2214.vb_b_34b_2ea_9b_83
pipeline-stage-view:2.34
pipeline-utility-steps:2.15.0
plain-credentials:182.v468b_97b_9dcb_8
plugin-util-api:3.8.0
postbuild-task:1.8
prism-api:1.29.0-8
pubsub-light:1.13
purge-job-history:1.6
rebuild:332.va_1ee476d8f6d
release:2.10.2
resource-disposer:0.23
run-condition:1.5
scm-api:696.v778d637b_a_762
script-security:1362.v67dc1f0e1b_b_3
simple-parameterized-builds-report:1.5
snakeyaml-api:2.2-121.v5a_68b_9300b_d4
sonar:2.17.2
sse-gateway:1.23
ssh-agent:333.v878b_53c89511
ssh-credentials:343.v884f71d78167
ssh-slaves:1.806.v2253cedd3295
sshd:3.322.v159e91f6a_550
structs:338.v848422169819
teamconcert:2.4.2
thinBackup:2.1.1
throttle-concurrents:2.14
timestamper:1.27
token-macro:400.v35420b_922dcb_
trilead-api:2.142.v748523a_76693
uno-choice:2.8.3
variant:60.v7290fc0eb_b_cd
workflow-aggregator:596.v8c21c963d92d
workflow-api:1336.vee415d95c521
workflow-basic-steps:1058.vcb_fc1e3a_21a_9
workflow-cps:3964.v0767b_4b_a_0b_fa_
workflow-durable-task-step:1371.vb_7cec8f3b_95e
workflow-job:1400.v7fd111b_ec82f
workflow-multibranch:773.vc4fe1378f1d5
workflow-scm-step:427.v4ca_6512e7df1
workflow-step-api:678.v3ee58b_469476
workflow-support:926.v9f4f9b_b_98c19
ws-cleanup:0.45
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

OS: Linux - 4.15.0-213-generic
Java: 17.0.10 - Eclipse Adoptium (OpenJDK 64-Bit Server VM)

### Reproduction steps

After Jenkins upgrade to 2.440.3 and pipeline-graph-view plugin update, Pipeline Graph is not visible on browser anymore. I have this error in Jenkins logs:

`Error while serving https://jenkinsurl/job/gradlefake/job/feature%252Ftestsonarp/193/pipeline-graph/tree
java.util.UnknownFormatConversionException: Conversion = 'F'
	at java.base/java.util.Formatter$FormatSpecifier.conversion(Unknown Source)
	at java.base/java.util.Formatter$FormatSpecifier.<init>(Unknown Source)`

### Expected Results

https://<url>/job/M0090_Gradle/job/develop/195/pipeline-graph/ Graph View OK.

### Actual Results

`Error while serving https://jenkinsurl/job/gradlefake/job/feature%252Ftestsonarp/193/pipeline-graph/tree
java.util.UnknownFormatConversionException: Conversion = 'F'
	at java.base/java.util.Formatter$FormatSpecifier.conversion(Unknown Source)
	at java.base/java.util.Formatter$FormatSpecifier.<init>(Unknown Source)`

**Comment by timja** [comment]
Can you provide a longer stacktrace please?

Do you have steps to reproduce this from scratch?
Do you know what version you upgraded from?

**Comment by apielmicroej** [comment]
I have updated from Jenkins 2.426.3 and Pipeline Graph View 215.217.v2f6b. 

I noticed that the graph still worked for builds prior to the update, it's only for new builds.
And in browser I saw that this call: `GET https://jenkins.cross/job/gradlefake/job/feature%252Ftestsonarp/203/pipeline-graph/tree` return an error 500.

See more complete logs: [log.txt](https://github.com/user-attachments/files/17133585/log.txt)

**Comment by timja** [comment]
Please upgrade to at least Jenkins 2.452.1 and then update the plugin to the latest version.

The area of code where the issue is occurring has been re-written on recent version.

**Comment by apielmicroej** [comment]
I have upgraded to 2.452.4 + plugin update and it's fine now. Thank you.
